spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:sqlserver://192.168.60.11:9567;databaseName=autodesk
    username: sa
    password: eng@soft9567!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  servlet:
    multipart:
      location: D:/upload/autodesk
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

uploadPath: D:\\upload\\autodesk\\