spring:
  main:
    banner-mode: off
  datasource:
    url:
    username:
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  servlet:
    multipart:
      location: D:/upload/autodesk
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

uploadPath: D:\\upload\\autodesk\\